dataset_yaml: "datasets/COCO/data.yaml"
epochs: 26
batch_size: 32
val_batch_size: 256
imgsz: 640
device: ['0']
train_ddp: False
master_addr: "localhost"
master_port: 12355
backend: "nccl"
patience: 50
experiments_root: "full_experiments/experiments_3010/coco_badge"
proctitle_midstr: "coco_badge"
proctitle_endstr_of: "seed"
seed: 1
strategy: "badge"
model_name: "yolo11s.yaml"
initial_labeled_count: 5914
max_rounds: 7
samples_per_round: 2957
num_inference: 6000
