dataset_yaml: "datasets/VOC/data.yaml"
epochs: 26
batch_size: 16
val_batch_size: 256
imgsz: 640
device: ['0']
train_ddp: False
master_addr: "localhost"
master_port: 12355
backend: "nccl"
patience: 50
experiments_root: "full_experiments/experiments_3010/voc_cdal"
proctitle_midstr: "voc_cdal"
proctitle_endstr_of: "seed"
seed: 1
strategy: "cdal"
model_name: "yolo11s.pt"
initial_labeled_count: 828
max_rounds: 7
samples_per_round: 414
num_inference: 6000

strategy_args:
  cdal:
    epsilon: 1e-8
    conf_threshold: 0.25

