dataset_yaml: "datasets/VOC/data.yaml"
epochs: 26
batch_size: 32
val_batch_size: 256
imgsz: 640
device: ['0']
train_ddp: False
master_addr: "localhost"
master_port: 12355
backend: "nccl"
patience: 50
experiments_root: "full_experiments/experiments_0301/voc_midprc"
proctitle_midstr: "voc_midprc"
proctitle_endstr_of: "seed"
seed: 1
strategy: "midprc"
model_name: "yolo11s.pt"
initial_labeled_count: 828
max_rounds: 7
samples_per_round: 414
num_inference: 6000

strategy_args:
  midprc:
    epsilon: 5.0
    lambda_weight: 1.0
    conf_threshold: 0.05
    iou_threshold: 0.5
    similarity_threshold: 0.85
    feature_dim: 512
