dataset_yaml: "datasets/VOC/data.yaml"
epochs: 26
batch_size: 16
val_batch_size: 256
imgsz: 640
device: ['0']
train_ddp: False
master_addr: "localhost"
master_port: 12355
backend: "nccl"
patience: 50
experiments_root: "full_experiments/experiments_1210/voc_coreset"
proctitle_midstr: "voc_coreset"
proctitle_endstr_of: "seed"
seed: 1
strategy: "coreset"
model_name: "yolo11s.pt"
initial_labeled_count: 828
max_rounds: 7
samples_per_round: 414
num_inference: 1000

strategy_args:
  ccms:
    feature_layers: ["model.9", "model.10"]