dataset_yaml: "datasets/VOC/data.yaml"
epochs: 26
batch_size: 16
val_batch_size: 256
imgsz: 640
device: ['0']
train_ddp: False
master_addr: "localhost"
master_port: 12355
backend: "nccl"
patience: 50
experiments_root: "full_experiments/experiments_3010/voc_fdal"
proctitle_midstr: "voc_fdal"
proctitle_endstr_of: "seed"
seed: 1
strategy: "fdal"
model_name: "yolo11s.pt"
initial_labeled_count: 828
max_rounds: 7
samples_per_round: 414
num_inference: 6000

strategy_args:
  fdal:
    supporter: "resnet18"
    supporter_epochs: 5
    supporter_batch_size: 1000000
    learn_alpha: True
    alpha_cap: 0.03125
    alpha_learning_rate: 0.1
    lambda_hyp: 0.99
    supporter_embedding_size: 32
    supporter_imgsz: 320
    one_alpha_cap: False
