dataset_yaml: "datasets/Cityscapes/data.yaml"
epochs: 26
batch_size: 16
val_batch_size: 64
imgsz: 640
device: ['0']
train_ddp: False
master_addr: "localhost"
master_port: 12355
backend: "nccl"
patience: 50
experiments_root: "full_experiments/experiments_1210/cityscapes_cdal"
proctitle_midstr: "cityscapes_cdal"
proctitle_endstr_of: "seed"
seed: 1
strategy: "cdal"
model_name: "yolo11n.pt"
initial_labeled_count: 149 # 5% of 2975
max_rounds: 7
samples_per_round: 75 # 2.5% of 2975
num_inference: 6000

strategy_args:
  cdal:
    epsilon: 1e-8
    conf_threshold: 0.25

